### ISSUE TITLE
Error when not setting the REDIS environment variable

### ISSUE THREAD

**Issue by nitzantomer** [kinecosystem/payment-service#7]
When running the service (`make`) after checking out the repo, this error occurs:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from payment import app
  File ".../payment/__init__.py", line 2, in <module>
    from . import blockchain
  File ".../payment/blockchain.py", line 2, in <module>
    from . import config
  File ".../payment/config.py", line 9, in <module>
    REDIS = os.environ['REDIS']
  File ".../virtualenvs/payment-service-MpmaPdVq/bin/../lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'REDIS'
```

Either add to the README (or wiki page) to set this var or do something like:
```
REDIS="localhost:6379" make
```
Or, add this as a default.

**Comment by doodyparizada** [comment]
thanks added a default to the Makefile
